### ISSUE TITLE
Non-dot matrix CLI reporter?

### ISSUE THREAD

**Issue by pretentiousgit** [rprieto/supersamples#23]
This is such a great library! My one issue is that it doesn't report back using the spec reporter for CLI - I would really prefer to use that. Is there any way we could include an optional different CLI reporter in this library, maybe with an -o tag or whatever? Editing the source seems harsh.

**Comment by rprieto** [comment]
Hi, sounds like a good suggestion!

`supersamples` is actually a reporter itself, and just "inherits" the `Dot` reporter ([see source](https://github.com/rprieto/supersamples/blob/master/lib/reporter.js#L8)). What about an entry in `supersamples.opts` to specify which base reporter to inherit from? This would only allow inheriting from one of Mocha's default reporters though, not specify your own for example. How does that sound?

**Comment by pretentiousgit** [comment]
That sounds great, thank you, and thanks again for this fantastic project.

**Comment by rprieto** [comment]
Thanks, it's great to hear it's useful!
I just published `v0.4.0`, let me know how it works.
