### ISSUE TITLE
captured and mixes request & response in beforeEach

### ISSUE THREAD

**Issue by littlexiang** [rprieto/supersamples#28]
when using beforeEach with Mocha, the pre-called request within beforeEach() is also combined into document

**Comment by littlexiang** [comment]
maybe I should not use supersamples in this way.
for now I added a DOC_MODE to skip other requests inline to avoid this problem

**Comment by littlexiang** [comment]
it should be a supertest/superagent bug instead

**Comment by rprieto** [comment]
I don't think we tested the behaviour of having HTTP requests made in `beforeEach`. I'll have a think whether we can ignore them (start capturing during the `it` phase only). Otherwise if you can skip that request it's great too :+1:

**Comment by littlexiang** [comment]
the deep cause I found is that superagent identifies requests by url
if more than 1 request with same url run in parallel, it got mixed up.....
so I just add a random get param ...
